#!/usr/bin/env ruby

require 'fileutils'
require 'securerandom'

file = "/tmp/#{SecureRandom.hex}.emacs-pager"

FileUtils.touch(file)

child_pid = fork do
  File.open(file, 'w') do |f|
    ARGF.each_line do |line|
      f.write(line)
    end
  end
end

puts 'reading into emacs...'

`emacsclient -e '(emacs-pager-page "#{file}" #{child_pid})'`

Process.waitall
